version: "3.7"
services:
  app:
    build:
      context: app
      args:
        - ENV=local
    init: true
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - app/.env
    environment:
      - BACKEND_HOST=http://localhost:8000
      - ENV=local
    command: ["./manage.py", "runserver", "0.0.0.0:8000"]
